EXCLUDED: set[str] = {
    "customitems/models/blocks/skafa.mcmtl.mcsb",
    "vegetation/models/wrk/optical.mic",
    "customitems/models/blocks/things/prestige_teleport.mcvd",
    "gloomycore/colliders/krovosos_clone/collider.mcvd",
    "gloomycore/colliders/pseudodog_clone/collider.mcvd",
    "gloomycore/colliders/tushkan_clone/collider.mcvd",
}

ARMS_HANDS_ONLY: set[str] = {
    "fp_walkcycles.mcvd",
    "wpn_fp_fists.mcvd",
    "wpn_fp_unarmed.mcvd",
}

ARMS_MODELS: dict[str, tuple[str, ...]] = {
    "wpn_fp_6x4meat.mcvd": ("meleeweapons/6x4/style_halloween23/6x4_halloween23.mcsb",),
    "wpn_fp_92fs.mcvd": ("weapons/beretta/beretta.mcsb",),
    "wpn_fp_93r.mcvd": ("weapons/beretta/beretta93.mcsb",),
    "wpn_fp_a545.mcvd": ("weapons/aek545/aek_545.mcsb",),
    "wpn_fp_a545_newyear2023.mcvd": ("weapons/aek545/style_newyear24/a545_newyear24.mcsb",),
    "wpn_fp_a545s.mcvd": ("weapons/aek545/aek_545.mcsb",),
    "wpn_fp_aek919k.mcvd": ("weapons/aek919/aek_919.mcsb",),
    "wpn_fp_aek965_1.mcvd": ("weapons/aek965/aek965.mcsb",),
    "wpn_fp_ak15_3dskin.mcvd": ("weapons/ak15/ak15.mcsb",),
    "wpn_fp_ak15_summer2026.mcvd": ("weapons/ak15/style_summer24/ak15_summer24.mcsb",),
    "wpn_fp_aks74u.mcvd": ("weapons/aksu/aksu.mcsb",),
    "wpn_fp_amb173dskin.mcvd": ("weapons/amb17/style_spring24/amb17_spring24.mcsb",),
    "wpn_fp_antiterror_skin_autumn24.mcvd": ("meleeweapons/antiterror/style_autumn24/antiterror_autumn24.mcsb",),
    "wpn_fp_arx160_gl.mcvd": ("weapons/arx160/arx160.mcsb",),
    "wpn_fp_arx160_summer25_gl.mcvd": ("weapons/arx160/style_summer25/arx160_summer25.mcsb",),
    "wpn_fp_aug_a1.mcvd": ("weapons/aug/aug.mcsb",),
    "wpn_fp_beluha.mcvd": ("weapons/detektor_model/beluga.mcsb",),
    "wpn_fp_benelli_shrt.mcvd": ("weapons/benelli_shorty/benelli_shorty.mcsb",),
    "wpn_fp_benelli_shrt2.mcvd": ("weapons/benelli_shorty/benelli_shorty.mcsb",),
    "wpn_fp_bm.mcvd": ("weapons/bm16/bm16.mcsb",),
    "wpn_fp_bm_obrez.mcvd": ("weapons/bm16/bm16_obrez.mcsb",),
    "wpn_fp_bm_obrez_frost.mcvd": ("weapons/bm16/bm16_obrez_frost.mcsb",),
    "wpn_fp_bolt_battery_big.mcvd": ("weapons/prestige/battery/battery.mcsb",),
    "wpn_fp_bolt_battery_small.mcvd": ("weapons/prestige/battery/battery.mcsb",),
    "wpn_fp_bolt_new_year_2025.mcvd": ("weapons/bolt/tree_toy/base.mcsb",),
    "wpn_fp_ChiappaTripple.mcvd": ("weapons/chiappa_triple_threat/tripple.mcsb",),
    "wpn_fp_cz75b.mcvd": ("weapons/cz75a/cz75a.mcsb",),
    "wpn_fp_daewoo_k2vet.mcvd": ("weapons/daewoo_k2/k2_damaged.mcsb",),
    "wpn_fp_deagle3dskin.mcvd": ("weapons/deagle/deagleXIX.mcsb",),
    "wpn_fp_deagleXIX_skin_autumn24.mcvd": ("weapons/deagle/style_autumn24/deagle_autumn24.mcsb",),
    "wpn_fp_deagleXIX_skin_spring24.mcvd": ("weapons/deagle/style_spring24/deagle_spring24.mcsb",),
    "wpn_fp_diversionniy.mcvd": ("meleeweapons/sabotage/sabotage.mcsb",),
    "wpn_fp_dp.mcvd": ("weapons/dp27/dp_27.mcsb",),
    "wpn_fp_dubina.mcvd": ("meleeweapons/club/club.mcsb",),
    "wpn_fp_eshka2.mcvd": ("weapons/eshka/eshka.mcsb",),
    "wpn_fp_eshka_3.mcvd": ("weapons/eshka/eshka.mcsb",),
    "wpn_fp_fal.mcvd": ("weapons/fnfal/fnfal.mcsb",),
    "wpn_fp_fal_old.mcvd": ("weapons/fnfal/old/fnfal.mcsb",),
    "wpn_fp_flaregun.mcvd": ("weapons/flaregun/flareguns.mcsb",),
    "wpn_fp_fn2000.mcvd": ("weapons/f2000/f2000.mcsb",),
    "wpn_fp_fn2000_hw23_3d_1.mcvd": ("weapons/f2000/style_halloween23/f2000_halloween23.mcsb",),
    "wpn_fp_fn2000_summer_24.mcvd": ("weapons/f2000/style_summer24/f2000_summer24.mcsb",),
    "wpn_fp_fn2kgl.mcvd": ("attachments/f2000/launcher/fn2kgl.mcsb",),
    "wpn_fp_gauss.mcvd": ("weapons/gauss/gaussgan.mcsb",),
    "wpn_fp_gerber_spring_26.mcvd": ("meleeweapons/downrange/style_mt/downrange_mt.mcsb",),
    "wpn_fp_glock_summer26.mcvd": ("weapons/glock/style_summer26/glock18_summer26.mcsb",),
    "wpn_fp_glock_winter25.mcvd": ("weapons/glock/style_winter26/glock18_winter26.mcsb",),
    "wpn_fp_glock.mcvd": ("weapons/glock/glock.mcsb",),
    "wpn_fp_glockdual.mcvd": ("weapons/glock/glock_dual.mcsb",),
    "wpn_fp_gp25.mcvd": ("attachments/launcher/gp25/gp25.mcsb",),
    "wpn_fp_guitar.mcvd": ("weapons/musical_instruments/gitara/gitara.mcsb",),
    "wpn_fp_hk416.mcvd": ("weapons/hk416/hk_416.mcsb",),
    "wpn_fp_hk417.mcvd": ("weapons/hk417/hk_417_anm.mcsb",),
    "wpn_fp_hooker.mcvd": ("meleeweapons/zseva2020/hooker_hands.mcsb",),
    "wpn_fp_hp_9x39.mcvd": ("weapons/hp/hp.mcsb",),
    "wpn_fp_inside_pb.mcvd": ("weapons/inside_pb/pb.mcsb",),
    "wpn_fp_izh_81.mcvd": ("weapons/izh81/izh81.mcsb",),
    "wpn_fp_jackhammer_autumn_25.mcvd": ("weapons/jackhammer/style_autumn25/jackhammer_autumn25.mcsb",),
    "wpn_fp_jagdkommando_winter24.mcvd": ("meleeweapons/jagd/style_winter25/jagd_winter25.mcsb",),
    "wpn_fp_karambit.mcvd": ("meleeweapons/kerambit/kerambit.mcsb",),
    "wpn_fp_kriss.mcvd": ("weapons/kriss/krisss.mcsb",),
    "wpn_fp_l85a1.mcvd": ("weapons/l86/l86.mcsb",),
    "wpn_fp_l86a1.mcvd": ("weapons/l86/l86.mcsb",),
    "wpn_fp_ledorub.mcvd": ("meleeweapons/iceaxe/iceaxe.mcsb",),
    "wpn_fp_lighter_ice.mcvd": ("weapons/bolt/lighter/ice.mcsb",),
    "wpn_fp_lighter_shock.mcvd": ("weapons/bolt/lighter/shock.mcsb",),
    "wpn_fp_long_knife.mcvd": ("meleeweapons/boneknife/boneknife.mcsb",),
    "wpn_fp_m1911.mcvd": ("weapons/colt/colt.mcsb",),
    "wpn_fp_m1a.mcvd": ("weapons/m14/m14_a.mcsb",),
    "wpn_fp_m1a_story.mcvd": ("weapons/m14/m14_sujet.mcsb",),
    "wpn_fp_m203.mcvd": ("attachments/launcher/m203/m203.mcsb",),
    "wpn_fp_m40a5.mcvd": ("weapons/m40/m40_anim.mcsb",),
    "wpn_fp_m60_spring_26.mcvd": ("weapons/m60/style_spring26/m60_spring26.mcsb",),
    "wpn_fp_m70.mcvd": ("weapons/Winchester_M70/Winchester_M70.mcsb",),
    "wpn_fp_mcmillan.mcvd": ("weapons/mcmilan/mcmilan.mcsb",),
    "wpn_fp_medicine.mcvd": ("weapons/medicine/aptechka.mcsb",),
    "wpn_fp_microuzi.mcvd": ("weapons/uzi_micro/micro_uzi.mcsb",),
    "wpn_fp_miniuzi.mcvd": ("weapons/uzi_mini/mini_uzi_mod.mcsb",),
    "wpn_fp_mk12.mcvd": ("weapons/deria_mk_12/deria_mk_12.mcsb",),
    "wpn_fp_mosin.mcvd": ("weapons/mosinka/mosinka.mcsb",),
    "wpn_fp_mosin_short.mcvd": ("weapons/mosinka/mosinka_korotkoya.mcsb",),
    "wpn_fp_mts116.mcvd": ("weapons/mc116/mc116.mcsb",),
    "wpn_fp_oc14-a1gp.mcvd": ("attachments/launcher/oc14-a1_gp/oc14-a1_gp.mcsb",),
    "wpn_fp_oc14_razryad.mcvd": ("weapons/ots14m/ots14m.mcsb",),
    "wpn_fp_oc14_razryad_autumn24.mcvd": ("weapons/ots14m/style_autumn24/ots14m_autumn24.mcsb",),
    "wpn_fp_oc14gp25.mcvd": ("attachments/groza/launcher/oc14gp25.mcsb",),
    "wpn_fp_p320.mcvd": ("weapons/sigsauerP320/sigsauerP320.mcsb",),
    "wpn_fp_pkp_skin.mcvd": ("weapons/pecheneg/pkp.mcsb",),
    "wpn_fp_pp1901.mcvd": ("weapons/pp19/pp19_hp.mcsb",),
    "wpn_fp_pp2k.mcvd": ("weapons/pp2000/pp2000.mcsb",),
    "wpn_fp_prestige_barricade.mcvd": ("weapons/prestige/barricade/prestige_barricade_fp.mcsb",),
    "wpn_fp_prestige_battery.mcvd": ("weapons/prestige/battery/battery.mcsb",),
    "wpn_fp_prestige_mine.mcvd": ("weapons/prestige/mine/prestige_mine_fp.mcsb",),
    "wpn_fp_prestige_scanner.mcvd": ("weapons/prestige/scanner/prestige_scanner_fp.mcsb",),
    "wpn_fp_ptrd.mcvd": ("weapons/ptrd/ptrd.mcsb",),
    "wpn_fp_rg6.mcvd": ("weapons/rg-6/rg_6.mcsb",),
    "wpn_fp_rgm40.mcvd": ("weapons/rgm40/rgm_40.mcsb",),
    "wpn_fp_roks.mcvd": ("weapons/roks3/roks3.mcsb",),
    "wpn_fp_rpg7.mcvd": ("weapons/rpg7/rpg_7.mcsb",),
    "wpn_fp_rpk16.mcvd": ("weapons/rpk16/rpk_16.mcsb",),
    "wpn_fp_rpk74.mcvd": ("weapons/rpk74/rpk_74.mcsb",),
    "wpn_fp_rpl-20.mcvd": ("weapons/rpl20/rpl20.mcsb",),
    "wpn_fp_rpl-20_ravent_24.mcvd": ("weapons/rpl20/style_spring24/rpl20_spring24.mcsb",),
    "wpn_fp_rsh12_summer_24.mcvd": ("weapons/rsh12/style_summer24/rsh12_summer24.mcsb",),
    "wpn_fp_runner.mcvd": ("meleeweapons/zseva2020/runner_hands.mcsb",),
    "wpn_fp_sa58_ctc_autumn25.mcvd": ("weapons/ctc/style_autumn25/ctc_autumn25.mcsb",),
    "wpn_fp_sa58_ctc_prestige.mcvd": ("weapons/ctc/style_prestige/ctc_prestige.mcsb",),
    "wpn_fp_saiga_12.mcvd": ("weapons/saiga12/saiga12.mcsb",),
    "wpn_fp_saiga_ravent_24.mcvd": ("weapons/saiga/saiga_3d_1/saiga_3d_1_style.mcsb",),
    "wpn_fp_scarh.mcvd": ("weapons/scar/Scar.mcsb",),
    "wpn_fp_scarl.mcvd": ("weapons/scar_l/Scar_l.mcsb",),
    "wpn_fp_scorpionVZ68.mcvd": ("weapons/vz68/vz68.mcsb",),
    "wpn_fp_sg550.mcvd": ("weapons/sig/SIG.mcsb",),
    "wpn_fp_shepot_knife.mcvd": ("meleeweapons/petal/petal.mcsb",),
    "wpn_fp_shorty.mcvd": ("weapons/mossberg_short/mossberg_short.mcsb",),
    "wpn_fp_sigsnip.mcvd": ("weapons/sig/sniper/SIG_SNIPERR.mcsb",),
    "wpn_fp_snowball(bolt)_24.mcvd": ("weapons/bolt/snowball/snowball.mcsb",),
    "wpn_fp_spectre.mcvd": ("weapons/spectre/spectre_m4.mcsb",),
    "wpn_fp_sr2.mcvd": ("weapons/sr-2/sr_2.mcsb",),
    "wpn_fp_storm_gp.mcvd": ("attachments/launcher/storm_gp/storm_gp.mcsb",),
    "wpn_fp_topor_peruna.mcvd": ("meleeweapons/battleaxe/battleaxe.mcsb",),
    "wpn_fp_toz.mcvd": ("weapons/toz34/toz34.mcsb",),
    "wpn_fp_ump.mcvd": ("weapons/ump/ump9.mcsb",),
    "wpn_fp_vityaz.mcvd": ("weapons/vityaz_sn/vityaz_sn.mcsb",),
    "wpn_fp_vss_spring25.mcvd": ("weapons/vss/style_spring25/vssm_spring25.mcsb",),
    "wpn_fp_vssng23.mcvd": ("weapons/vss/style_newyear24/vss_newyear24.mcsb",),
    "wpn_fp_woofercut.mcvd": ("weapons/ability_items/woofer/woofer.mcsb",),
    "wpn_fp_xm8s.mcvd": ("weapons/xm8sop/xm8sopmod.mcsb",),
    "wpn_ppk20_winter25.mcvd": ("weapons/ppk20/style_winter25/ppk20_winter25.mcsb",),
    "wpn_sa20_rhythm.mcvd": ("weapons/sa20_rhythm/sa20_rhythm.mcsb",),
    "wpn_sa20_takt.mcvd": ("weapons/sa20_takt/sa20_takt.mcsb",),
    "wpn_fp_aug9.mcvd": (
        "weapons/aug/aug9_a3.mcsb",
        "weapons/aug/aug9mm.mcsb",
    ),
    "wpn_fp_chain_wave.mcvd": (
        "weapons/bolt/chain/chain.mcsb",
        "weapons/bolt/chain/wave.mcsb",
    ),
    "wpn_fp_daewoo_k2.mcvd": (
        "weapons/daewoo_k2/k2.mcsb",
        "weapons/daewoo_k2/k2c1.mcsb",
    ),
    "wpn_fp_eglm.mcvd": (
        "attachments/eglm/eglm.mcsb",
        "attachments/launcher/eglm/eglm.mcsb",
    ),
    "wpn_fp_m203_famas.mcvd": (
        "attachments/famas/famas_m203.mcsb",
        "attachments/launcher/m203/m203_famas.mcsb",
    ),
    "wpn_fp_SN2.mcvd": (
        "weapons/skaner/skaner_2.mcsb",
        "weapons/skaner/skaner_2_a.mcsb",
    ),
    "wpn_fp_sv98.mcvd": (
        "weapons/sv98/sv_98.mcsb",
        "weapons/sv98/old_sv98/sv_98.mcsb",
    ),
    "wpn_fp_vsk.mcvd": (
        "weapons/vsk/9a91.mcsb",
        "weapons/vsk/9a91_ny23.mcsb",
        "weapons/vsk/vsk94.mcsb",
    ),
}
