from scfile.app.localization import LANG, Lang


DATA: dict[Lang, dict[str, str]] = {
    "EN": {
        "tab.convert": "Converter",
        "tab.animate": "Animations",
        "tab.mapcache": "Map cache",
        "tab.maptiles": "2D Map",
        "tab.settings": "Settings",
        "label.convert.sources": "Sources",
        "label.convert.settings": "Settings",
        "label.convert.output": "Output Path",
        "label.convert.onconflict": "On Name Collision",
        "label.convert.onconflict.hint": "Action on output file name conflict",
        "label.animate.mcvd": "Animation",
        "label.animate.mcal": "Animation",
        "label.animate.mcsb": "Model",
        "label.animate.weapon": "Weapon",
        "label.animate.hands": "Hands",
        "label.animate.head": "Head",
        "label.animate.output": "Output",
        "label.mapcache.source": "SC map cache",
        "label.mapcache.output": "Minecraft world regions",
        "label.maptiles.source": "SC map tiles",
        "label.maptiles.region": "Region",
        "label.maptiles.map": "Map",
        "label.maptiles.output": "Map image",
        "label.maptiles.quality": "Quality",
        "label.maptiles.compression": "Compression",
        "label.documentation": "docs",
        "label.experimental": "🧪",
        "label.settings.general": "General",
        "label.settings.paths": "Paths",
        "label.settings.game": "Game Folder",
        "label.settings.game.hint": "Used to locate assets",
        "label.settings.export": "Export Folder",
        "label.settings.export.hint": "Used as default export folder",
        "label.guide": "Usage guide ↗",
        "mode.animate.arms": "Weapon First Person",
        "mode.animate.body": "Skeletal",
        "mode.animate.face": "Facial",
        "button.convert": "CONVERT",
        "button.animate": "EXPORT",
        "button.mapcache": "MERGE",
        "button.maptiles": "ASSEMBLE",
        "button.convert.add.files": "+ Files",
        "button.convert.add.folder": "+ Folder",
        "button.convert.remove.source": "Remove source from list",
        "format.models": "Models",
        "format.textures": "Textures",
        "format.images": "Images",
        "format.archive": "Archives",
        "format.nbt": "NBT",
        "feature.skeleton": "Skeleton",
        "feature.animation": "Animation",
        "option.convert.output.origin": "Alongside source file",
        "option.convert.output.tree": "Keep subfolder structure",
        "option.convert.output.dump": "Dump into one folder",
        "option.convert.onconflict.replace": "Replace",
        "option.convert.onconflict.rename": "Rename",
        "option.convert.onconflict.skip": "Skip",
        "option.animate.body.preserve": "Preserve Clips",
        "option.animate.body.preserve.hint": "Keep technical poses and animation layers",
        "option.mapcache.biomes": "Biomes",
        "option.mapcache.biomes.hint": "Export biome data",
        "option.mapcache.backup": "Backup regions",
        "option.mapcache.backup.hint": "Keep originals .mca when replacing",
        "option.settings.resolve": "Resolve Paths",
        "option.settings.resolve.hint": "Automatically adjust paths to data folders",
        "option.settings.verbose": "Verbose Output",
        "option.settings.verbose.hint": "Show every processed file in the console",
        "tooltip.task.busy": "Another task is running",
        "tooltip.form.required": "Required field",
        "tooltip.form.invalid": "Fix errors in the form",
        "tooltip.experimental": "Experimental feature",
        "tooltip.browse.directory": "LMB: Select directory\nRMB: Open in Explorer",
        "tooltip.browse.file": "LMB: Select file\nRMB: Open in Explorer",
        "tooltip.convert.invalid.sources": "Add sources to convert",
        "tooltip.convert.invalid.targets": "No compatible files found",
        "tooltip.convert.invalid.output": "Specify an output folder",
        "tooltip.animate.invalid.mcvd": "Specify an MCVD animation",
        "tooltip.animate.invalid.mcal": "Specify an MCAL animation",
        "tooltip.animate.invalid.mcsb": "Specify an MCSB model",
        "tooltip.animate.invalid.arms": "Specify a weapon or hands model",
        "tooltip.animate.invalid.output": "Specify an output GLB file",
        "tooltip.mapcache.invalid.source": "No .mdat files found in specified folder",
        "tooltip.mapcache.invalid.output": "Specify an output folder",
        "tooltip.mapcache.scanning": "Scanning for .mdat files",
        "tooltip.maptiles.invalid.source": "No map tiles found in specified folder",
        "tooltip.maptiles.invalid.output": "Specify an output image file",
        "tooltip.maptiles.region": "Specify game folder to choose a region",
        "tooltip.maptiles.map": "Specify game folder to choose a map",
        "tooltip.maptiles.empty.map": "No map tile folders found in the selected game",
        "tooltip.maptiles.fixed.map": "The map is fixed by the source path",
        "warning.convert.gamedir": "Output path is inside game directory",
        "warning.convert.overlap": "Output path overlaps with a source",
        "warning.animate.invalid.weaponfp": "Selected file may not be a suitable weapon fp animation",
        "warning.animate.overwrite": "Output model will be overwritten",
        "warning.mapcache.overwrite.world": 'Selected regions in world "{world}" will be overwritten',
        "warning.mapcache.overwrite.folder": 'Selected regions in folder "{world}" will be overwritten',
        "warning.mapcache.invalid.mcworld": "The selected folder is not a Minecraft world region folder",
        "warning.maptiles.overwrite": "Output image will be overwritten",
        "dialog.convert.add.files": "Select files",
        "dialog.convert.add.folder": "Select folder",
        "dialog.convert.output": "Output Folder",
        "dialog.animate.mcvd": "Select MCVD animation",
        "dialog.animate.mcal": "Select MCAL animation",
        "dialog.animate.mcsb": "Select MCSB model",
        "dialog.animate.output": "Save animated model",
        "dialog.mapcache.source": "SC map cache",
        "dialog.mapcache.output": "Minecraft world regions",
        "dialog.maptiles.source": "Select map tiles folder",
        "dialog.maptiles.output": "Save map image",
        "dialog.settings.game": "STALCRAFT game folder",
        "dialog.settings.export": "Select default export folder",
        "update.checking": "Checking for updates...",
        "update.uptodate": "You are using the latest version",
        "update.available": "Update available",
        "update.error": "Update check failed",
        "update.manual": "Check manually",
        "placeholder.path": "Specify path...",
        "placeholder.maptiles.map": "Select a map...",
        "placeholder.maptiles.region": "Select a region...",
        "convert.sources": "Drag & Drop files and folders\nor use buttons above",
        "mapcache.format": "Minecraft Java 1.12.2+ (Anvil 1343)",
        "mapcache.limitation": "Terrain geometry with approximate blocks.",
        "mapcache.credit": "Research: TeamDima, BoJIwEbNuK7",
        "maptiles.estimate": "Estimated size: ~{size} MB",
        "maptiles.map.global_map": "Global Map",
        "maptiles.map.map": "Zone Map",
        "maptiles.map.map-arena_raven": "Raven Arena",
        "maptiles.map.map-dungeon_bolota_tutorial": "Swamps tutorial",
        "maptiles.map.map-incident": "Dead Time",
        "maptiles.map.map-kolizei": "Transit",
        "maptiles.map.map-nbolota": "The Graveyard",
        "maptiles.map.map-new_bar": "Bar",
        "maptiles.map.map-prestige": "Coliseum",
        "maptiles.map.map-reichstag": "Reichstag",
        "maptiles.map.map-sovetpunk": "GOST-17",
        "maptiles.map.map_bar_save": "Legacy Bar",
    },
    "RU": {
        "tab.convert": "Конвертер",
        "tab.animate": "Анимации",
        "tab.mapcache": "Кэш карты",
        "tab.maptiles": "2D Карта",
        "tab.settings": "Настройки",
        "label.convert.sources": "Источники",
        "label.convert.settings": "Настройки",
        "label.convert.output": "Путь сохранения",
        "label.convert.onconflict": "При совпадении имени",
        "label.convert.onconflict.hint": "Действие при совпадении имени выходного файла",
        "label.animate.mcvd": "Анимации",
        "label.animate.mcal": "Анимации",
        "label.animate.mcsb": "Модель",
        "label.animate.weapon": "Оружие",
        "label.animate.hands": "Руки",
        "label.animate.head": "Голова",
        "label.animate.output": "Результат",
        "label.mapcache.source": "SC кэш карты",
        "label.mapcache.output": "Minecraft регионы мира",
        "label.maptiles.source": "SC тайлы карты",
        "label.maptiles.region": "Регион",
        "label.maptiles.map": "Карта",
        "label.maptiles.output": "Изображение карты",
        "label.maptiles.quality": "Качество",
        "label.maptiles.compression": "Сжатие",
        "label.documentation": "docs",
        "label.experimental": "🧪",
        "label.settings.general": "Общее",
        "label.settings.paths": "Пути",
        "label.settings.game": "Папка игры",
        "label.settings.game.hint": "Используется для поиска ассетов",
        "label.settings.export": "Папка экспорта",
        "label.settings.export.hint": "Используется как папка экспорта по умолчанию",
        "label.guide": "Руководство по использованию ↗",
        "mode.animate.arms": "Оружие от первого лица",
        "mode.animate.body": "Скелетная",
        "mode.animate.face": "Лицевая",
        "button.convert": "КОНВЕРТИРОВАТЬ",
        "button.animate": "ЭКСПОРТИРОВАТЬ",
        "button.mapcache": "ОБЪЕДИНИТЬ",
        "button.maptiles": "СОБРАТЬ",
        "button.convert.add.files": "+ Файлы",
        "button.convert.add.folder": "+ Папка",
        "button.convert.remove.source": "Удалить источник из списка",
        "format.models": "Модели",
        "format.textures": "Текстуры",
        "format.images": "Изображения",
        "format.archive": "Архивы",
        "format.nbt": "NBT",
        "feature.skeleton": "Скелет",
        "feature.animation": "Анимация",
        "option.convert.output.origin": "Рядом с оригинальным файлом",
        "option.convert.output.tree": "Сохранять структуру подпапок",
        "option.convert.output.dump": "В одну плоскую папку",
        "option.convert.onconflict.replace": "Перезапись",
        "option.convert.onconflict.rename": "Копия",
        "option.convert.onconflict.skip": "Пропуск",
        "option.animate.body.preserve": "Исходные клипы",
        "option.animate.body.preserve.hint": "Сохранять технические позы и слои анимации",
        "option.mapcache.biomes": "Биомы",
        "option.mapcache.biomes.hint": "Экспортировать данные биомов",
        "option.mapcache.backup": "Резервные копии",
        "option.mapcache.backup.hint": "Сохранять оригинальные .mca перед заменой",
        "option.settings.resolve": "Исправление путей",
        "option.settings.resolve.hint": "Автоматически корректировать путь до папки с данными",
        "option.settings.verbose": "Подробный вывод",
        "option.settings.verbose.hint": "Показывать в консоли обработку каждого файла",
        "tooltip.task.busy": "Выполняется другая задача",
        "tooltip.form.required": "Обязательное поле",
        "tooltip.form.invalid": "Исправьте ошибки в форме",
        "tooltip.experimental": "Экспериментальная функция",
        "tooltip.browse.directory": "ЛКМ: Выбрать папку\nПКМ: Открыть в проводнике",
        "tooltip.browse.file": "ЛКМ: Выбрать файл\nПКМ: Открыть в проводнике",
        "tooltip.convert.invalid.sources": "Добавьте источники для конвертации",
        "tooltip.convert.invalid.targets": "Подходящие файлы не найдены",
        "tooltip.convert.invalid.output": "Укажите папку для сохранения",
        "tooltip.animate.invalid.mcvd": "Укажите анимацию MCVD",
        "tooltip.animate.invalid.mcal": "Укажите анимацию MCAL",
        "tooltip.animate.invalid.mcsb": "Укажите модель MCSB",
        "tooltip.animate.invalid.arms": "Укажите модель оружия или рук",
        "tooltip.animate.invalid.output": "Укажите выходной файл GLB",
        "tooltip.mapcache.invalid.source": "В указанной папке не найдены файлы .mdat",
        "tooltip.mapcache.invalid.output": "Укажите папку для сохранения",
        "tooltip.mapcache.scanning": "Поиск файлов .mdat",
        "tooltip.maptiles.invalid.source": "В указанной папке не найдены тайлы карты",
        "tooltip.maptiles.invalid.output": "Укажите выходной файл изображения",
        "tooltip.maptiles.region": "Укажите папку игры, чтобы выбрать регион",
        "tooltip.maptiles.map": "Укажите папку игры, чтобы выбрать карту",
        "tooltip.maptiles.empty.map": "В выбранной игре не найдены папки с тайлами карты",
        "tooltip.maptiles.fixed.map": "Карта задана исходным путём",
        "warning.convert.gamedir": "Путь сохранения находится внутри папки игры",
        "warning.convert.overlap": "Путь сохранения пересекается с одним из источников",
        "warning.animate.invalid.weaponfp": "Выбранный файл возможно не является weapon fp анимацией",
        "warning.animate.overwrite": "Выходная модель будет перезаписана",
        "warning.mapcache.overwrite.world": 'Выбранные регионы мира "{world}" будут перезаписаны',
        "warning.mapcache.overwrite.folder": 'Выбранные регионы папки "{world}" будут перезаписаны',
        "warning.mapcache.invalid.mcworld": "Указанная папка не является регионами мира Minecraft",
        "warning.maptiles.overwrite": "Выходное изображение будет перезаписано",
        "dialog.convert.add.files": "Выбор файлов",
        "dialog.convert.add.folder": "Выбор папки",
        "dialog.convert.output": "Папка результатов",
        "dialog.animate.mcvd": "Выбор MCVD анимации",
        "dialog.animate.mcal": "Выбор MCAL анимации",
        "dialog.animate.mcsb": "Выбор MCSB модели",
        "dialog.animate.output": "Сохранение анимированной модели",
        "dialog.mapcache.source": "Кэш карты SC",
        "dialog.mapcache.output": "Регионы мира Minecraft",
        "dialog.maptiles.source": "Выбор папки с тайлами карты",
        "dialog.maptiles.output": "Сохранение изображения карты",
        "dialog.settings.game": "Папка игры STALCRAFT",
        "dialog.settings.export": "Папка экспорта по умолчанию",
        "update.checking": "Проверка обновлений...",
        "update.uptodate": "Вы используете последнюю версию",
        "update.available": "Доступно обновление",
        "update.error": "Ошибка проверки обновлений",
        "update.manual": "Проверьте вручную",
        "placeholder.path": "Укажите путь...",
        "placeholder.maptiles.map": "Выберите карту...",
        "placeholder.maptiles.region": "Выберите регион...",
        "convert.sources": "Перетащите файлы и папки сюда\nлибо добавьте их кнопками выше",
        "mapcache.format": "Minecraft Java 1.12.2+ (Anvil 1343)",
        "mapcache.limitation": "Базовая геометрия приближёнными блоками.",
        "mapcache.credit": "Помощь в исследовании: TeamDima, BoJIwEbNuK7",
        "maptiles.estimate": "Примерный размер: ~{size} МБ",
        "maptiles.map.global_map": "Глобальная карта",
        "maptiles.map.map": "Карта Зоны",
        "maptiles.map.map-arena_raven": "Арена Ворона",
        "maptiles.map.map-dungeon_bolota_tutorial": "Болота обучение",
        "maptiles.map.map-incident": "Мёртвое время",
        "maptiles.map.map-kolizei": "Транзит",
        "maptiles.map.map-nbolota": "Могильник",
        "maptiles.map.map-new_bar": "Бар",
        "maptiles.map.map-prestige": "Колизей",
        "maptiles.map.map-reichstag": "Рейхстаг",
        "maptiles.map.map-sovetpunk": "ГОСТ-17",
        "maptiles.map.map_bar_save": "Старый Бар",
    },
}


def get(key: str, fallback: str | None = None) -> str:
    return DATA.get(LANG, {}).get(key, fallback if fallback is not None else key)
