import locale
from typing import Literal


type Lang = Literal["EN"] | Literal["RU"]


def _resolve_lang() -> Lang:
    try:
        lang = (locale.getlocale()[0] or "").lower()
        return "RU" if lang.startswith("russian") or lang.startswith("ru_") else "EN"

    except Exception:
        return "EN"


LANG: Lang = _resolve_lang()

DATA: dict[Lang, dict[str, str]] = {
    "EN": {
        "tab.converter": "Convert Files",
        "tab.animate": "Animations",
        "tab.mapcache": "Map Cache",
        "tab.settings": "Settings",
        "label.sources": "Sources",
        "label.settings": "Settings",
        "label.settings.game_root": "Game Folder",
        "label.settings.export": "Export Folder",
        "section.settings.general": "General",
        "section.settings.paths": "Paths",
        "label.output": "Output Path",
        "label.onconflict": "On Name Collision",
        "label.animate.animation": "Animation (.mcvd)",
        "label.animate.skeletal": "Animation (.mcal)",
        "label.animate.model": "Weapon (.mcsb)",
        "label.animate.hands": "Hands (.mcsb)",
        "label.animate.head": "Head (.mcsb)",
        "label.animate.character": "Model (.mcsb)",
        "label.animate.output": "Output (.glb)",
        "label.animate.raw_clips": "Raw clips",
        "mode.animate.body": "SKELETAL",
        "mode.animate.fp": "FIRST PERSON",
        "mode.animate.lipsync": "FACIAL",
        "label.mapcache.source": "SC map cache (.mdat)",
        "label.mapcache.output": "Minecraft world regions (.mca)",
        "button.add_files": "+ Files",
        "button.add_folder": "+ Folder",
        "button.remove_source": "Remove source from list",
        "button.convert": "CONVERT",
        "button.animate": "EXPORT",
        "button.mapcache": "MERGE",
        "format.models": "Models",
        "format.textures": "Textures",
        "format.images": "Images",
        "format.texarr": "Texture Array",
        "format.nbt": "NBT Data",
        "feature.skeleton": "Skeleton",
        "feature.animation": "Animation",
        "option.output.origin": "Alongside source file",
        "option.output.tree": "Keep subfolder structure",
        "option.output.flat": "Single flat folder",
        "option.onconflict.overwrite": "Overwrite",
        "option.onconflict.skip": "Skip",
        "option.onconflict.rename": "Rename",
        "option.mapcache.raw": "Raw Block IDs",
        "option.settings.resolve_paths": "Resolve Paths",
        "option.settings.verbose": "Verbose Output",
        "hint.onconflict": "Action on output file name conflict",
        "hint.mapcache.raw": "Keep original block IDs instead of lookup table replacement",
        "hint.settings.game_root": "Used to locate assets",
        "hint.settings.export": "Used as the default export folder",
        "hint.settings.resolve_paths": "Automatically adjust paths to data folders",
        "hint.settings.verbose": "Show every processed file in the console",
        "tooltip.path_browse": "LMB: Select directory\nRMB: Open in Explorer",
        "tooltip.file_browse": "LMB: Select file\nRMB: Open in Explorer",
        "tooltip.invalid.output": "Specify an output folder",
        "tooltip.invalid.form": "Fix the errors in the form",
        "tooltip.invalid.sources": "Add sources to convert",
        "tooltip.invalid.targets": "No compatible files found",
        "tooltip.task.busy": "Another task is running",
        "tooltip.animate.invalid.animation": "Specify an MCVD animation",
        "tooltip.animate.invalid.skeletal": "Specify an MCAL animation",
        "tooltip.animate.invalid.models": "Specify a weapon or hands model",
        "tooltip.animate.invalid.model": "Specify an MCSB model",
        "tooltip.animate.invalid.additional": "Additional model must be an MCSB file",
        "tooltip.animate.invalid.output": "Specify an output GLB file",
        "hint.animate.raw_clips": "Keep technical poses and animation layers",
        "tooltip.mapcache.invalid.output": "Specify an output folder",
        "tooltip.mapcache.invalid.source": "No .mdat files found in specified folder",
        "tooltip.mapcache.scanning": "Scanning for .mdat files",
        "warning.gamedir": "Output path is inside game directory",
        "warning.output_overlap": "Output path overlaps with a source",
        "warning.mapcache.overwrite.world": 'Regions in world "{world}" will be overwritten!',
        "warning.mapcache.overwrite.folder": 'Regions in folder "{world}" will be overwritten!',
        "warning.mapcache.invalid_world": "The selected folder is not a Minecraft world region folder",
        "warning.animate.not_fp": "Selected file may not be a suitable weapon fp animation",
        "dialog.add_files": "Select files",
        "dialog.add_folder": "Select folder",
        "dialog.output": "Output Folder",
        "dialog.animate.animation": "Select MCVD animation",
        "dialog.animate.skeletal": "Select MCAL animation",
        "dialog.animate.model": "Select model",
        "dialog.animate.hands": "Select hands model",
        "dialog.animate.head": "Select head model",
        "dialog.animate.character": "Select model",
        "dialog.animate.output": "Save animated model",
        "dialog.mapcache.source": "SC map cache",
        "dialog.mapcache.output": "Minecraft world regions",
        "dialog.settings.game_root": "STALCRAFT game folder",
        "dialog.settings.export": "Select default export folder",
        "update.checking": "Checking for updates...",
        "update.uptodate": "You are using the latest version",
        "update.available": "Update available",
        "update.error": "Update check failed",
        "update.manual": "Check manually",
        "placeholder.path": "Specify path...",
        "converter.hint": "Drag & Drop files and folders\nor use buttons above",
        "mapcache.info": "Format: Anvil 1343 (Minecraft 1.12.2+)\nExperimental decoder designed for basic geometry preview",
    },
    "RU": {
        "tab.converter": "Конвертер файлов",
        "tab.animate": "Анимации",
        "tab.mapcache": "Кэш карты",
        "tab.settings": "Настройки",
        "label.sources": "Источники",
        "label.settings": "Настройки",
        "label.settings.game_root": "Папка игры",
        "label.settings.export": "Папка экспорта",
        "section.settings.general": "Общее",
        "section.settings.paths": "Пути",
        "label.output": "Путь сохранения",
        "label.onconflict": "При совпадении имени",
        "label.animate.animation": "Анимация (.mcvd)",
        "label.animate.skeletal": "Анимация (.mcal)",
        "label.animate.model": "Оружие (.mcsb)",
        "label.animate.hands": "Руки (.mcsb)",
        "label.animate.head": "Голова (.mcsb)",
        "label.animate.character": "Модель (.mcsb)",
        "label.animate.output": "Результат (.glb)",
        "label.animate.raw_clips": "Исходные клипы",
        "mode.animate.fp": "ОТ ПЕРВОГО ЛИЦА",
        "mode.animate.lipsync": "ЛИЦЕВАЯ",
        "mode.animate.body": "СКЕЛЕТНАЯ",
        "label.mapcache.source": "SC кэш карты (.mdat)",
        "label.mapcache.output": "Minecraft регионы мира (.mca)",
        "button.add_files": "+ Файлы",
        "button.add_folder": "+ Папка",
        "button.remove_source": "Удалить источник из списка",
        "button.convert": "КОНВЕРТИРОВАТЬ",
        "button.animate": "ЭКСПОРТИРОВАТЬ",
        "button.mapcache": "ОБЪЕДИНИТЬ",
        "format.models": "Модели",
        "format.textures": "Текстуры",
        "format.images": "Изображения",
        "format.texarr": "Массив Текстур",
        "format.nbt": "NBT Данные",
        "feature.skeleton": "Скелет",
        "feature.animation": "Анимация",
        "option.output.origin": "Рядом с оригинальным файлом",
        "option.output.tree": "Сохранять структуру подпапок",
        "option.output.flat": "В одну плоскую папку",
        "option.onconflict.overwrite": "Перезапись",
        "option.onconflict.skip": "Пропуск",
        "option.onconflict.rename": "Копия",
        "option.mapcache.raw": "Исходные IDs",
        "option.settings.resolve_paths": "Исправление путей",
        "option.settings.verbose": "Подробный вывод",
        "hint.onconflict": "Действие при совпадении имени выходного файла",
        "hint.mapcache.raw": "Сохранять оригинальные ID блоков вместо подмены по таблице",
        "hint.settings.game_root": "Используется для поиска ассетов",
        "hint.settings.export": "Используется как папка экспорта по умолчанию",
        "hint.settings.resolve_paths": "Автоматически корректировать путь до папки с данными",
        "hint.settings.verbose": "Показывать в консоли обработку каждого файла",
        "tooltip.path_browse": "ЛКМ: Выбрать папку\nПКМ: Открыть в проводнике",
        "tooltip.file_browse": "ЛКМ: Выбрать файл\nПКМ: Открыть в проводнике",
        "tooltip.invalid.output": "Укажите папку для сохранения",
        "tooltip.invalid.form": "Исправьте ошибки в форме",
        "tooltip.invalid.sources": "Добавьте источники для конвертации",
        "tooltip.invalid.targets": "Подходящие файлы не найдены",
        "tooltip.task.busy": "Выполняется другая задача",
        "tooltip.animate.invalid.animation": "Укажите анимацию MCVD",
        "tooltip.animate.invalid.skeletal": "Укажите анимацию MCAL",
        "tooltip.animate.invalid.models": "Укажите модель оружия или рук",
        "tooltip.animate.invalid.model": "Укажите модель MCSB",
        "tooltip.animate.invalid.additional": "Дополнительная модель должна быть файлом MCSB",
        "tooltip.animate.invalid.output": "Укажите выходной файл GLB",
        "hint.animate.raw_clips": "Сохранять технические позы и слои анимации",
        "tooltip.mapcache.invalid.output": "Укажите папку для сохранения",
        "tooltip.mapcache.invalid.source": "В указанной папке не найдены файлы .mdat",
        "tooltip.mapcache.scanning": "Поиск файлов .mdat",
        "warning.gamedir": "Путь сохранения находится внутри папки игры",
        "warning.output_overlap": "Путь сохранения пересекается с одним из источников",
        "warning.mapcache.overwrite.world": 'Регионы мира "{world}" будут перезаписаны!',
        "warning.mapcache.overwrite.folder": 'Регионы папки "{world}" будут перезаписаны!',
        "warning.mapcache.invalid_world": "Указанная папка не является регионами мира Minecraft",
        "warning.animate.not_fp": "Выбранный файл возможно не является weapon fp анимацией",
        "dialog.add_files": "Выбор файлов",
        "dialog.add_folder": "Выбор папки",
        "dialog.output": "Папка результатов",
        "dialog.animate.animation": "Выбор анимации MCVD",
        "dialog.animate.skeletal": "Выбор анимации MCAL",
        "dialog.animate.model": "Выбор модели",
        "dialog.animate.hands": "Выбор модели рук",
        "dialog.animate.head": "Выбор модели головы",
        "dialog.animate.character": "Выбор модели",
        "dialog.animate.output": "Сохранение анимированной модели",
        "dialog.mapcache.source": "Кэш карты SC",
        "dialog.mapcache.output": "Регионы мира Minecraft",
        "dialog.settings.game_root": "Папка игры STALCRAFT",
        "dialog.settings.export": "Выберите папку экспорта по умолчанию",
        "update.checking": "Проверка обновлений...",
        "update.uptodate": "Вы используете последнюю версию",
        "update.available": "Доступно обновление",
        "update.error": "Ошибка проверки обновлений",
        "update.manual": "Проверьте вручную",
        "placeholder.path": "Укажите путь...",
        "converter.hint": "Перетащите файлы и папки сюда\nлибо добавьте их кнопками выше",
        "mapcache.info": "Формат: Anvil 1343 (Minecraft 1.12.2+)\nЭкспериментальный декодер для просмотра базовой геометрии",
    },
}


def get(key: str) -> str:
    return DATA.get(LANG, {}).get(key, key)
