class ScFileException(Exception): ...

# * basic
class SourceFileNotFound(ScFileException): ...
class UnsupportedFormat(ScFileException): ...
class InvalidSignature(ScFileException): ...
class FileIsEmpty(ScFileException): ...

# * reader
class ReaderError(ScFileException): ...
class McsaStringError(ReaderError): ...
class OlStringError(ReaderError): ...

# * .ol files
class OlFileError(ScFileException): ...
class OlUnsupportedFormat(OlFileError): ...
class OlDXNXYError(OlFileError): ...
class OlDXNXYSize(OlDXNXYError): ...
class OlDXNXYNotSquare(OlDXNXYError): ...

# * .mcsa files
class McsaFileError(ScFileException): ...
class McsaUnsupportedVersion(McsaFileError): ...
class McsaUnsupportedFlags(McsaFileError): ...
class McsaUnsupportedLinkCount(McsaFileError): ...
