import locale
from typing import Literal, TypeAlias


Lang: TypeAlias = Literal["EN"] | Literal["RU"]


def _resolve_lang() -> Lang:
    try:
        lang = (locale.getlocale()[0] or "").lower()
        return "RU" if lang.startswith("russian") or lang.startswith("ru_") else "EN"

    except Exception:
        return "EN"


LANG: Lang = _resolve_lang()

DATA: dict[Lang, dict[str, str]] = {
    "EN": {
        "tab.converter": "Convert Files",
        "tab.mapcache": "Map Cache",
        "label.sources": "Sources",
        "label.settings": "Settings",
        "label.output": "Output Path",
        "label.onconflict": "On Name Collision",
        "label.mapcache.source": "SC map cache",
        "label.mapcache.output": "Minecraft world regions",
        "button.add_files": "+ Files",
        "button.add_folder": "+ Folder",
        "button.remove_source": "Remove source from list",
        "button.convert": "CONVERT",
        "button.mapcache.merge": "CONVERT",
        "format.models": "Models",
        "format.textures": "Textures",
        "format.images": "Images",
        "format.texarr": "TextureArray",
        "format.nbt": "NBT Data",
        "feature.skeleton": "Skeleton",
        "feature.animation": "Animation",
        "option.output.origin": "Alongside source file",
        "option.output.tree": "Keep subfolder structure",
        "option.output.flat": "Single flat folder",
        "option.onconflict.overwrite": "Overwrite",
        "option.onconflict.skip": "Skip",
        "option.onconflict.rename": "Rename",
        "option.mapcache.resolve": "Resolve Paths",
        "option.mapcache.raw": "Raw Block IDs",
        "hint.onconflict": "Action on output file name conflict",
        "hint.mapcache.resolve": "Auto-complete path to data folder",
        "hint.mapcache.raw": "Keep original block IDs instead of lookup table replacement",
        "tooltip.path_browse": "LMB: Select directory\nRMB: Open in Explorer",
        "tooltip.invalid.output": "Specify an output folder",
        "tooltip.invalid.sources": "Add sources to convert",
        "tooltip.invalid.targets": "No compatible files found",
        "tooltip.mapcache.invalid.output": "Specify an output folder",
        "tooltip.mapcache.invalid.source": "No .mdat files found in specified folder",
        "warning.gamedir": "Output path is inside game directory",
        "warning.output_overlap": "Output path overlaps with a source",
        "warning.mapcache.overwrite": 'Regions in world "{world}" will be overwritten!',
        "warning.mapcache.invalid_world": "No Minecraft world found at specified path",
        "dialog.add_files": "Select files",
        "dialog.add_folder": "Select folder",
        "dialog.output": "Output Folder",
        "dialog.mapcache.source": "SC map cache",
        "dialog.mapcache.output": "Minecraft world regions",
        "update.checking": "Checking for updates...",
        "update.uptodate": "You are using the latest version",
        "update.available": "Update available",
        "update.error": "Update check failed",
        "update.manual": "Check manually",
        "placeholder.path": "Specify path...",
        "converter.hint": "Drag & Drop files and folders\nor use buttons above",
        "mapcache.info": "Format: Anvil 1343 (Minecraft 1.12.2+)\nExperimental decoder designed for basic geometry preview.\nFull environment replication or accurate block states are NOT planned.",
    },
    "RU": {
        "tab.converter": "Конвертер файлов",
        "tab.mapcache": "Кэш карты",
        "label.sources": "Источники",
        "label.settings": "Настройки",
        "label.output": "Путь сохранения",
        "label.onconflict": "При совпадении имени",
        "label.mapcache.source": "SC кэш карты",
        "label.mapcache.output": "Minecraft регионы мира",
        "button.add_files": "+ Файлы",
        "button.add_folder": "+ Папка",
        "button.remove_source": "Удалить источник из списка",
        "button.convert": "КОНВЕРТИРОВАТЬ",
        "button.mapcache.merge": "КОНВЕРТИРОВАТЬ",
        "format.models": "Модели",
        "format.textures": "Текстуры",
        "format.images": "Изображения",
        "format.texarr": "Массив Текстур",
        "format.nbt": "NBT Данные",
        "feature.skeleton": "Скелет",
        "feature.animation": "Анимация",
        "option.output.origin": "Рядом с оригинальным файлом",
        "option.output.tree": "Сохранять структуру подпапок",
        "option.output.flat": "В одну плоскую папку",
        "option.onconflict.overwrite": "Перезапись",
        "option.onconflict.skip": "Пропуск",
        "option.onconflict.rename": "Копия",
        "option.mapcache.resolve": "Исправление путей",
        "option.mapcache.raw": "Исходные ID",
        "hint.onconflict": "Действие при совпадении имени выходного файла",
        "hint.mapcache.resolve": "Автоматически достраивать путь до папки с данными",
        "hint.mapcache.raw": "Сохранять исходные ID блоков вместо подмены по таблице",
        "tooltip.path_browse": "ЛКМ: Выбрать папку\nПКМ: Открыть в проводнике",
        "tooltip.invalid.output": "Укажите папку для сохранения",
        "tooltip.invalid.sources": "Добавьте источники для конвертации",
        "tooltip.invalid.targets": "Подходящие файлы не найдены",
        "tooltip.mapcache.invalid.output": "Укажите папку для сохранения",
        "tooltip.mapcache.invalid.source": "В указанной папке не найдены файлы .mdat",
        "warning.gamedir": "Путь сохранения находится внутри папки игры",
        "warning.output_overlap": "Путь сохранения пересекается с одним из источников",
        "warning.mapcache.overwrite": 'Регионы мира "{world}" будут перезаписаны!',
        "warning.mapcache.invalid_world": "По указанному пути не найдены данные мира Minecraft",
        "dialog.add_files": "Выбор файлов",
        "dialog.add_folder": "Выбор папки",
        "dialog.output": "Папка результатов",
        "dialog.mapcache.source": "Кэш карты SC",
        "dialog.mapcache.output": "Регионы мира Minecraft",
        "update.checking": "Проверка обновлений...",
        "update.uptodate": "Вы используете последнюю версию",
        "update.available": "Доступно обновление",
        "update.error": "Ошибка проверки обновлений",
        "update.manual": "Проверьте вручную",
        "placeholder.path": "Укажите путь...",
        "converter.hint": "Перетащите файлы и папки сюда\nлибо добавьте их кнопками выше",
        "mapcache.info": "Формат: Anvil 1343 (Minecraft 1.12.2+)\nЭкспериментальный декодер для просмотра базовой геометрии.\nИдеальное воссоздание окружения и состояний блоков НЕ планируется.",
    },
}


def get(key: str) -> str:
    return DATA.get(LANG, {}).get(key, key)
