"""
Data structures for 3D model content.
"""

from .animation import AnimationClip, ModelAnimation
from .enums import (
    AnimationRotation,
    AnimationTranslation,
    Feature,
    LinkSpace,
    ModelUnits,
    SkeletonSpace,
    UVOrigin,
    UVSign,
)
from .matrices import create_rotation_matrix, create_transform_matrix, euler_to_quat
from .mesh import BlendShape, MeshBounds, ModelMesh
from .scene import ModelScene, SceneScales
from .skeleton import ROOT_BONE_ID, ModelSkeleton, SkeletonBone
from .types import (
    AnimationRotations,
    AnimationTimes,
    AnimationTranslations,
    BindPose,
    BlendVertexMap,
    BonesMapping,
    Colors,
    EulerAngles,
    FeatureFlags,
    Features,
    InverseBindMatrices,
    Links,
    LinksIds,
    LinksWeights,
    LocalBoneId,
    MorphWeights,
    Polygons,
    Quaternion,
    RotationMatrix,
    SkeletonBoneId,
    TransformMatrix,
    Vector2D,
    Vector3D,
    Vector4D,
)


__all__ = (
    "AnimationClip",
    "BlendShape",
    "MeshBounds",
    "ModelAnimation",
    "ModelMesh",
    "ModelScene",
    "SceneScales",
    "SkeletonBone",
    "ModelSkeleton",
    "ROOT_BONE_ID",
    "ModelUnits",
    "Feature",
    "AnimationRotations",
    "AnimationTimes",
    "AnimationTranslations",
    "BindPose",
    "BlendVertexMap",
    "BonesMapping",
    "Colors",
    "EulerAngles",
    "FeatureFlags",
    "Features",
    "InverseBindMatrices",
    "Links",
    "LinksIds",
    "LinksWeights",
    "LocalBoneId",
    "MorphWeights",
    "Polygons",
    "Quaternion",
    "RotationMatrix",
    "SkeletonBoneId",
    "TransformMatrix",
    "Vector2D",
    "Vector3D",
    "Vector4D",
    "AnimationRotation",
    "AnimationTranslation",
    "LinkSpace",
    "SkeletonSpace",
    "UVOrigin",
    "UVSign",
    "create_rotation_matrix",
    "create_transform_matrix",
    "euler_to_quat",
)
