name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: Linux
            artifact: linux-binary
            binary: scfile_linux_x64
            cmd: mv dist/scfile scfile_linux_x64 && chmod +x scfile_linux_x64
          - os: windows-latest
            name: Windows
            artifact: windows-binary
            binary: scfile_windows_x64.exe
            cmd: mv dist/scfile.exe scfile_windows_x64.exe

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build Binary
        run: uv run --group build scripts/build.py

      - name: Prepare Artifact
        shell: bash
        run: ${{ matrix.cmd }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.binary }}
          retention-days: 1

  publish-package:
    name: Publish PyPi
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && !contains(github.ref_name, 'dev')

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build Package
        run: uv build -o ./dist/

      - name: Publish Package
        run: uv publish ./dist/*
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  publish-release:
    name: Publish GitHub
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Define Metadata
        id: meta
        shell: bash
        run: |
          export TZ="Europe/Moscow"
          echo "date=$(date +'%B %d, %Y')" >> "$GITHUB_OUTPUT"
          echo "time=$(date +'%H:%M (GMT+3)')" >> "$GITHUB_OUTPUT"

          if [[ "${{ github.ref_name }}" == *"dev"* ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "title=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "title=Release ${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        if: github.ref_type == 'tag' || startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.meta.outputs.title }}
          prerelease: ${{ steps.meta.outputs.prerelease }}
          generate_release_notes: true
          body: |
            ## `${{ steps.meta.outputs.date }}` `${{ steps.meta.outputs.time }}`
            ${{ steps.meta.outputs.prerelease == 'true' && '' }}
            ${{ steps.meta.outputs.prerelease == 'true' && '> [!WARNING]' || '' }}
            ${{ steps.meta.outputs.prerelease == 'true' && '> This build is auto-generated from latest commit and not tested.' || '' }}
          files: |
            artifacts/windows-binary/scfile_windows_x64.exe
            artifacts/linux-binary/scfile_linux_x64
